# -*- mode: python ; coding: utf-8 -*-
"""
Cross-platform build spec for any-loc (Windows single .exe + macOS .app bundle).

Parameterized via the environment variable ANYLOC_VARIANT:
  - "test"  -> name=AnyLocTest,  no admin manifest  (validatable without elevation)
  - "final" -> name=AnyLoc,      admin manifest on Windows  (the shippable app)

Packaging shape differs per OS:
  - Windows: ONEFILE (a single AnyLoc.exe). Everything is packed into the exe and
    unpacked to a temp dir at launch. Easiest for end users — just one file to
    double-click, no folder to keep together.
  - macOS:   ONEDIR (COLLECT) wrapped in a proper AnyLoc.app bundle so users can
    drop it into /Applications. dylibs run from inside the .app.

Set ANYLOC_ONEDIR=1 to force the old Windows onedir (folder) build instead — needed
on locked-down machines with WDAC/Application Control that block running code from
%TEMP% (onefile unpacks there). The default is onefile.

Elevation model (handled at runtime by launcher.py, NOT here):
  - Windows: uac_admin=True bakes an "requireAdministrator" manifest -> UAC prompt.
  - macOS:   the app re-launches itself under `sudo` in Terminal (no manifest needed).
"""
import os
import sys
from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

IS_WINDOWS = sys.platform.startswith("win")
IS_MACOS = sys.platform == "darwin"

# App version — bump here on release. Referenced by the macOS .app bundle below.
# Keep this in sync with VERSION in scripts/build-mac.sh (used for the .pkg name).
APP_VERSION = "1.1.0"

VARIANT = os.environ.get("ANYLOC_VARIANT", "final")
if VARIANT == "test":
    APP_NAME, UAC = "AnyLocTest", False
    BUNDLE_ID = "com.anyloc.app.test"
else:
    APP_NAME, UAC = "AnyLoc", True
    BUNDLE_ID = "com.anyloc.app"

# Windows ships as a single .exe by default (easiest for end users). Set
# ANYLOC_ONEDIR=1 to fall back to a folder build for locked-down WDAC machines.
WIN_ONEFILE = IS_WINDOWS and os.environ.get("ANYLOC_ONEDIR", "") not in ("1", "true", "yes")

# App icon for the Windows exe (generated by scripts/make_icon.py). None on macOS.
EXE_ICON = os.path.join("web", "icon.ico") if IS_WINDOWS and os.path.exists(os.path.join("web", "icon.ico")) else None

datas, binaries, hiddenimports = [], [], []
datas += [("web", "web")]

# Bundle adb (Android Debug Bridge) so Android mode works with no separate SDK
# install. android_backend.find_adb() looks for it at the _MEIPASS root when
# frozen, so we ship it there (dest "."). Windows adb needs its two helper DLLs
# next to it. Use `datas` (verbatim copy) rather than `binaries`: adb is a
# standalone exe that doesn't want PyInstaller's shared-lib dependency analysis
# (which silently drops it). Skipped gracefully if the vendor files aren't present.
_adb_files = []
if IS_WINDOWS:
    _adb_files = [os.path.join("vendor", "win", f)
                  for f in ("adb.exe", "AdbWinApi.dll", "AdbWinUsbApi.dll")]
elif IS_MACOS:
    _adb_files = [os.path.join("vendor", "mac", "adb")]
for _p in _adb_files:
    if os.path.exists(_p):
        datas += [(_p, ".")]
    else:
        print(f"[spec] warn: {_p} missing — Android mode won't work in this build")

# Packages to fully collect. `apple_compress` is macOS-only (pyimg4 pulls it in
# on Darwin for LZFSE); harmless to list — collect_all just warns if absent.
_collect_pkgs = [
    "pymobiledevice3", "pytun_pmd3", "developer_disk_image", "ipsw_parser",
    "qh3", "uvicorn", "construct", "opack2", "bpylist2", "pyimg4",
    "remotezip2", "pykdebugparser",
]
if IS_MACOS:
    _collect_pkgs.append("apple_compress")

# Fully collect data + binaries + submodules for the runtime-dynamic packages.
for pkg in _collect_pkgs:
    try:
        d, b, h = collect_all(pkg)
        datas += d; binaries += b; hiddenimports += h
    except Exception as e:
        print(f"[spec] warn collect_all({pkg!r}): {e}")

# Ship .dist-info metadata for packages that read their own version at import
# time (importlib.metadata.version(...)). Missing metadata = import crash.
# NB: apple_compress does exactly this on macOS -> it MUST be here for Darwin.
_meta_pkgs = [
    "pyimg4", "ipsw_parser", "developer_disk_image", "pymobiledevice3",
    "remotezip2", "construct", "qh3", "uvicorn", "pytun_pmd3", "opack2",
    "bpylist2", "pykdebugparser", "cryptography", "pyusb",
    # These read their own version via importlib.metadata at import time with no
    # fallback; bundling their metadata prevents PackageNotFoundError crashes if
    # any code path reaches them in the frozen app. (Cheap insurance.)
    "prompt_toolkit", "readchar",
]
if IS_MACOS:
    _meta_pkgs.append("apple_compress")

for pkg in _meta_pkgs:
    try:
        datas += copy_metadata(pkg)
    except Exception as e:
        print(f"[spec] warn copy_metadata({pkg!r}): {e}")

hiddenimports += collect_submodules("uvicorn")
hiddenimports += [
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets.websockets_impl",
    "uvicorn.lifespan.on",
    "uvicorn.loops.asyncio",
]

# Our own modules are imported lazily (inside functions) in a few places, so make
# sure PyInstaller bundles them even if static analysis misses a path.
hiddenimports += ["backend", "backend_base", "ios_backend", "android_backend"]

# Tunnel-service modules: names have shifted across pymobiledevice3 versions
# (e.g. `core_device_tunnel_service` was folded into `tunnel_service` around
# v9.33). Only add the ones that actually import, so the spec stays clean and
# version-proof on both Windows and macOS instead of logging hard ERRORs.
import importlib.util as _ilu
for _mod in (
    "pymobiledevice3.remote.tunnel_service",
    "pymobiledevice3.remote.core_device_tunnel_service",
    "pymobiledevice3.remote.userspace_tunnel",
):
    try:
        if _ilu.find_spec(_mod) is not None:
            hiddenimports.append(_mod)
    except Exception:
        pass

a = Analysis(
    ["launcher.py"],
    pathex=["."],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    excludes=[
        "tkinter", "matplotlib", "pytest",
        # Heavy libs present in this dev env but unused by any-loc.
        # (IPython is intentionally NOT excluded — pmd3 hard-imports it.)
        "torch", "numpy", "pandas", "scipy", "numba", "llvmlite", "av",
        "notebook", "sympy", "sklearn", "cv2", "PIL",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data)

if WIN_ONEFILE:
    # Single-file Windows build: bundle EVERYTHING (scripts + libs + datas) into
    # one AnyLoc.exe. At launch the bootloader unpacks to a temp dir and runs from
    # there. No COLLECT folder, no .app — just the one file the user double-clicks.
    exe = EXE(
        pyz, a.scripts, a.binaries, a.datas, [],
        name=APP_NAME,
        console=True,       # keep the log console visible
        uac_admin=UAC,      # requireAdministrator manifest -> UAC prompt
        icon=EXE_ICON,
        upx=False,
    )
else:
    # Onedir build: exe holds only the bootstrap; the rest lives beside it in the
    # COLLECT folder. Used for macOS (.app) and for WDAC-locked Windows machines
    # (ANYLOC_ONEDIR=1), where running unpacked code from %TEMP% is blocked.
    exe = EXE(
        pyz, a.scripts, [],
        exclude_binaries=True,
        name=APP_NAME,
        console=True,       # keep logs visible (Windows console / macOS Terminal)
        uac_admin=UAC,      # Windows-only manifest; ignored on macOS
        icon=EXE_ICON,
    )
    coll = COLLECT(exe, a.binaries, a.datas, strip=False, upx=False, name=APP_NAME)

    # On macOS, wrap the onedir COLLECT output in a real .app bundle so users can
    # drop it into /Applications and double-click it. launcher.py does the sudo
    # elevation.
    if IS_MACOS:
        app = BUNDLE(
            coll,
            name=f"{APP_NAME}.app",
            icon=None,
            bundle_identifier=BUNDLE_ID,
            version=APP_VERSION,
            info_plist={
                "CFBundleName": APP_NAME,
                "CFBundleDisplayName": APP_NAME,
                "CFBundleShortVersionString": APP_VERSION,
                "CFBundleVersion": APP_VERSION,
                "NSHighResolutionCapable": True,
                "LSMinimumSystemVersion": "11.0",
                # Not a background-only agent: we want it to appear/activate
                # normally and be allowed to talk to the local network + spawn
                # Terminal.
                "LSBackgroundOnly": False,
            },
        )
